site_name: CivicActions Style Guide
site_url: https://civicactions-style-guide.readthedocs.io/en/latest/

repo_url: https://github.com/civicactions/style-guide/

theme:
    name: readthedocs
    include_homepage_in_sidebar: True
    navigation_depth: 4
    collapse_navigation: True
    titles_only: False
    sticky_navigation: True

extra_css:
    - css/extra.css

plugins:
    - search

nav:
    - Style Guide:
        - Introduction: README.md
            - Brand overview: introduction/brand-overview.md
            - Accessibility: introduction/accessibility.md
        - Brand: 
            - Logo: brand/logo.md
            - Typography: brand/typography.md
            - Colors: brand/colors.md
        - Templates:
            - Google Slides decks: templates/google-slides.md
            - Google Docs styles: templates/google-docs.md
        - Assets:
            - Photography: assets/photography.md
            - Video: assets/video.md
        
