site_name: CivicActions Style Guide
site_url: https://civicactions-style-guide.readthedocs.io/en/latest/

repo_url: https://github.com/civicactions/style-guide/

theme:
    name: readthedocs

extra_css:
    - css/extra.css

plugins:
    - search

pages:
    - Style Guide:
        - Welcome: README.md
        - Brand: styleguide/brand/logo.md
            - Logo: styleguide/brand/logo.md
            - Colors: styleguide/brand/colors.md
            - Typography: collateral/typography.md
            - Photography: collateral/photography.md
            - Video: collateral/video.md
        - Design System: 
            - Components: styleguide/designsystem/components.md
        - Templates:
            - Digital: styleguide/templates/digital.md
            - Print: styleguide/templates/print.md
        
